import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const pokemon = localFont({
  src: "../../public/fonts/Pokemon.woff2",
  variable: "--font-pokemon",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${pokemon.variable} antialiased`}>{children}</body>
    </html>
  );
}
